# Checks if there are duplicate human proteins encoded by human genes. Duplicates determined by equal Uniprot ID.
SELECT ?gene ?uniprot ?protein_aff ?total WHERE {
  {
  SELECT distinct ?uniprot (count(?uniprot) as ?total) WHERE {
    ?gene wdt:P703 wd:Q5 ;
          wdt:P279 wd:Q7187 ;
          wdt:P688 ?protein . 
    ?protein wdt:P352 ?uniprot ;
             wdt:P703 wd:Q5 .
    }
    Group BY ?uniprot
  }

  ?protein_aff wdt:P352 ?uniprot .
  ?gene wdt:P688 ?protein_aff ;
        wdt:P703 wd:Q5 .

  FILTER (?total > 1)
 }
 ORDER BY ?gene