# query detect human genes encoding for mouse proteins (P688).

PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX v: <http://www.wikidata.org/prop/statement/>

SELECT ?gene ?uniprot ?protein_aff ?total WHERE {
  {
  SELECT distinct ?uniprot (count(?uniprot) as ?total) WHERE {
    ?gene wdt:P703 wd:Q83310 ;
          wdt:P279 wd:Q7187 ;
          wdt:P688 ?protein . 
    ?protein wdt:P352 ?uniprot ;
             wdt:P703 wd:Q5 .
    }
    Group BY ?uniprot
  }

  ?protein_aff wdt:P352 ?uniprot .
  ?gene wdt:P688 ?protein_aff ;
        wdt:P703 wd:Q5 .

  FILTER (?total > 1)
 }
 ORDER BY ?gene
